### PR TITLE
Need option to set user agent in the browser window

### PR DESCRIPTION
**Pull request by pranavwani**
@mironal OAuth2 application does not allow default electron user agent (Issue comes in Google)

### CODE REVIEW

**Comment by pranavwani** [comment]
@mironal From here, can set the user agent: https://www.electronjs.org/docs/api/browser-window#winloadurlurl-options

**Comment by mironal** [comment]
@pranavwani Thanks!

**Comment by pranavwani** [comment]
@mironal can you please publish this on npm

**Comment by mironal** [comment]
@pranavwani I have published a new version!

**Comment by pranavwani** [comment]
@mironal Thanks 🙂

**Pull request merged**
